SpeechToText.Web/Models/PlayerViewModel.cs
using System;
using System.Collections.Generic;
using System.Threading;
using SpeechToText.Web.Controllers;

namespace SpeechToText.Web.Models
{
    public class PlayerViewModel
    {
        public List<TranscriptViewModel> Transcripts { get; set; }
            = new List<TranscriptViewModel>();

        public string MediaUrl { get; set; }

        public PlayerViewModel(List<TranscriptViewModel> transcripts, string mediaUrl)
        {
            Transcripts = transcripts;
            MediaUrl = mediaUrl;
        }

        public PlayerViewModel()
        {
            
        }
    }

    public class TranscriptViewModel
    {
        public int Index { get; set; }

        public string Content { get; set; }

        public TimeSpan StartTime { get; set; }
        
        public TimeSpan EndTime { get; set; }

        public TranscriptViewModel()
        {
            
        }

        public TranscriptViewModel(RecognizeResult m)
        {
            Index = m.Index;
            Content = m.Content;
            StartTime = m.StartTime;
            EndTime = m.EndTime;
        }
    }
}

SpeechToText.Web/Controllers/PlayerController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SpeechToText.Web.Domain;
using SpeechToText.Web.Models;
using SpeechToText.Web.Services;

namespace SpeechToText.Web.Controllers
{
    public class PlayerController : Controller
    {
        private readonly ILogger<PlayerController> _logger;
        private readonly IWebHostEnvironment _environment;

        public PlayerController(ILogger<PlayerController> logger, IWebHostEnvironment webHostEnvironment)
        {
            _logger = logger;
            _environment = webHostEnvironment;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var viewModel = new PlayerViewModel();
            return View(viewModel);
        }

        [HttpPost]
        [DisableRequestSizeLimit]
        public async Task<IActionResult> Index(IFormFile file)
        {
            if (file.Length <= 0)
                return View(new PlayerViewModel());

            var uploads = Path.Combine(_environment.WebRootPath, "uploads");
            List<RecognizeResult> results = new List<RecognizeResult>();
            PlayerViewModel viewModel = null;
            var filePath = Path.Combine(uploads, file.FileName);
            var mediaUrl = $"uploads/{file.FileName}";

            using (var fileStream = new FileStream(filePath, FileMode.Create))
                await file.CopyToAsync(fileStream);

            _logger.LogDebug($"Get Duration ..... ");
            var duration = VideoHelper.GetDuration(filePath);
            var currentTime = new TimeSpan();
            _logger.LogDebug($"Duration: {duration?.ToString("G")}");
            _logger.LogDebug("Start split and extract audio");

            List<Task<RecognizeResult>> tasks = new List<Task<RecognizeResult>>();
            
            // split and extract audio
            var index = 1;
            while (currentTime < duration)
            {
                var outputFile = Path.Combine(uploads,
                    $"{file.FileName}-{DateTime.Now:ddMMyyyyHHmmss}-{index}.wav");

                await VideoConverter.VideoConverter.ExtractAudio(filePath, outputFile,
                    currentTime.TotalSeconds,
                    30);
                _logger.LogDebug($"Add {outputFile} to output list");
                
                tasks.Add(RecognizeAsync(outputFile, index, currentTime.TotalSeconds,
                    currentTime.TotalSeconds + 30));
                
                currentTime = currentTime.Add(new TimeSpan(0, 0, 30));
                index++;
            }

            _logger.LogDebug("Start Recognize text");
            // upload to GCS or call directly from local
            var excutedTask = tasks.ToList();
            _logger.LogDebug($"Fetch list task");
            while (excutedTask.Count > 0)
            {
                _logger.LogDebug($"Number of task in list {excutedTask.Count}");
                // Identify the first task that completes.
                Task<RecognizeResult> firstFinishedTask = await Task.WhenAny(excutedTask);
                // ***Remove the selected task from the list so that you don't
                // process it more than once.
                excutedTask.Remove(firstFinishedTask);
                // Await the completed task.
                results.Add(await firstFinishedTask);
            }

            viewModel = new PlayerViewModel(
                results.Select(x => new TranscriptViewModel(x)).ToList(),
                mediaUrl);

            return View(viewModel);
        }
 
        private Task<RecognizeResult> RecognizeAsync(string filePath, int index, double startTime, double endTime)
        {
            return Task.Run(() =>
            {
                _logger.LogDebug($"Start new thread for {filePath}");
                var r = Recognize.SyncRecognize(filePath);
                _logger.LogDebug($"End new thread for {filePath}");

                return new RecognizeResult
                {
                    Index = index,
                    Content = r,
                    StartTime = TimeSpan.FromSeconds(startTime),
                    EndTime = TimeSpan.FromSeconds(endTime)
                };
            });
        }
    }
}

SpeechToText.Web/Views/Player/Index.cshtml
@model PlayerViewModel
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="hadesker">

    <title>Page Title</title>
    <link href="~/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.plyr.io/3.5.6/plyr.css"/>
    <link rel="stylesheet" href="~/css/style.css">
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body >
<header class="">
    <div class="container">
        <nav class="nav">
            <a class="nav-link active" href="#">TRANG CHỦ</a>
            <a class="nav-link" href="#">GIỚI THIỆU</a>
            <a class="nav-link" href="#">QUẢN LÝ CÔNG VĂN</a>
        </nav>
    </div>
</header>
<div class="container">
    <div class="row">
        <div class="col-8">

            <div class="Upload">
                <form method="post" enctype="multipart/form-data" asp-controller="Player" asp-action="Index">
                    <div class="input-group mb-3">
                        <div class="custom-file">
                            <input type="file" name="file" class="custom-file-input" id="inputGroupFile01" multiple/>
                            <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
                        </div>
                        <div class="input-group-append">
                            <input type="submit" class="input-group-text" value="Upload"/>
                        </div>
                    </div>
                </form>
            </div>
            <div class="video">
                <video id="player" playsinline controls>
                    <source src="@Model.MediaUrl" type="video/mp4"/>
                </video>
            </div>
            <div class="lyric">
                <p>@Html.Raw(string.Join("<br/>", Model.Transcripts.Select(x => x.Content).ToList()))</p>
            </div>

        </div>
        <div class="col-4">
            <div class="timeline">
                <h5>Các chương trình</h5>
                <div class="list-timeline">
                    <div class="item">
                        <a href="">
                            <img src="https://photo-resize-zmp3.zadn.vn/w240_r16x9_jpeg/thumb_video/8/2/b/7/82b7f655f25e2bafa46aaa0fa03d9a3d.jpg" alt="">
                        </a>
                        <div class="caption">
                            <a href="">Chương trình 1</a>
                            <time>01:10:20</time>
                        </div>
                    </div>
                    <div class="item">
                        <a href="">
                            <img src="https://photo-resize-zmp3.zadn.vn/w240_r16x9_jpeg/thumb_video/8/2/b/7/82b7f655f25e2bafa46aaa0fa03d9a3d.jpg" alt="">
                        </a>
                        <div class="caption">
                            <a href="">Chương trình 1</a>
                            <time>01:10:20</time>
                        </div>
                    </div>
                    <div class="item">
                        <a href="">
                            <img src="https://photo-resize-zmp3.zadn.vn/w240_r16x9_jpeg/thumb_video/8/2/b/7/82b7f655f25e2bafa46aaa0fa03d9a3d.jpg" alt="">
                        </a>
                        <div class="caption">
                            <a href="">Chương trình 1</a>
                            <time>01:10:20</time>
                        </div>
                    </div>
                    <div class="item">
                        <a href="">
                            <img src="https://photo-resize-zmp3.zadn.vn/w240_r16x9_jpeg/thumb_video/8/2/b/7/82b7f655f25e2bafa46aaa0fa03d9a3d.jpg" alt="">
                        </a>
                        <div class="caption">
                            <a href="">Chương trình 1</a>
                            <time>01:10:20</time>
                        </div>
                    </div>
                    <div class="item">
                        <a href="">
                            <img src="https://photo-resize-zmp3.zadn.vn/w240_r16x9_jpeg/thumb_video/8/2/b/7/82b7f655f25e2bafa46aaa0fa03d9a3d.jpg" alt="">
                        </a>
                        <div class="caption">
                            <a href="">Chương trình 1</a>
                            <time>01:10:20</time>
                        </div>
                    </div>
                    <div class="item">
                        <a href="">
                            <img src="https://photo-resize-zmp3.zadn.vn/w240_r16x9_jpeg/thumb_video/8/2/b/7/82b7f655f25e2bafa46aaa0fa03d9a3d.jpg" alt="">
                        </a>
                        <div class="caption">
                            <a href="">Chương trình 1</a>
                            <time>01:10:20</time>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="~/js/bootstrap.min.js"></script>
<script src="https://cdn.plyr.io/3.5.6/plyr.polyfilled.js"></script>
<script src="~/js/main.js"></script>
</body>
</html>